output_dir: ./results/24.10.21_check_new_kinds_long/

datasets:
  - name: newer_college_2020/01_short_experiment
    # length: 1000

pipelines:
  - pipeline: cleaner
    wrap: kiss
    deskew: false
    max_num_iterations: 200
    sweep:
      clean: [False]
      intensity_residual: [-2, -1, 0, 1, 2]
      intensity_metric: [-2, -1, 0, 1, 2]
