output_dir: ./results/24.10.16_cleaner/

datasets:
  - name: newer_college_2020/01_short_experiment
    length: 1000

pipelines:
  - pipeline: cleaner
    wrap: kiss
    deskew: false
    max_num_iterations: 200
    sweep:
      clean: [True, False]
      intensity_residual: [0, 1, 2]
      intensity_metric: [0, 1, 2]