[project]
name = "evalio"
authors = [{ name = "Easton Potokar", email = "contagon6@gmail.com" }]
maintainers = [{ name = "Easton Potokar", email = "contagon6@gmail.com" }]
version = "0.0.1"
description = "Evaluate Lidar-Inertial Odometry on public datasets"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argcomplete>=3.3.0",
    "numpy",
    "pyyaml>=6.0",
    "rosbags>=0.10",
    "tabulate>=0.9",
    "tqdm>=4.66",
]
keywords = [
    "lidar",
    "odometry",
    "evaluation",
    "inertial",
    "dataset",
    "robotics",
]
license = { file = "LICENSE.txt" }

[project.optional-dependencies]
fetch = ["gdown>=5.2.0"]
vis = ["rerun-sdk>=0.18.2"]

[build-system]
requires = ["scikit-build-core>=0.8", "pybind11", "pybind11-stubgen", "numpy"]
build-backend = "scikit_build_core.build"

[project.scripts]
evalio = "evalio.cli:main"

# -------------- Tools -------------- #
# building
[tool.scikit-build]
minimum-version = "0.8"
build-dir = "build/{wheel_tag}"
sdist.include = ["cpp/evalio/pipelines-src/*"]

[tool.scikit-build.cmake.define]
EVALIO_BUILD_PYTHON = true

[tool.cibuildwheel]
# TODO: Add mac support eventually
build = "cp*-manylinux_x86_64"
skip = "cp310-*"
manylinux-x86_64-image = "ghcr.io/contagon/evalio_manylinux_2_28_x86_64:latest"
test-requires = "pytest>=8.3.5 scipy>=1.15.2"
test-command = "evalio ls pipelines && pytest {project}/tests"

# local developtment
[tool.uv]
dev-dependencies = [
    "cmake>=3.30.3",
    "compdb>=0.2.0",
    "pybind11-stubgen>=2.5.1",
    "ruff>=0.6.8",
    "types-pyyaml>=6.0.12.20240917",
    "types-tabulate>=0.9.0.20240106",
    "types-tqdm>=4.66.0.20240417",
    "pytest>=8.3.5",
    "scipy>=1.15.2",
    "scipy-stubs>=1.15.2.1",
]

[tool.ruff]
exclude = ["cpp/**/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
