[project]
name = "evalio"
authors = [{ name = "Easton Potokar", email = "contagon6@gmail.com" }]
maintainers = [{ name = "Easton Potokar", email = "contagon6@gmail.com" }]
version = "0.1.0"
description = "Evaluate Lidar-Inertial Odometry on public datasets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy<2", "rosbags>=0.10.4", "tqdm>=4.66.5"]
keywords = [
    "lidar",
    "odometry",
    "evaluation",
    "inertial",
    "dataset",
    "robotics",
]
# TODO
# license = {file = "LICENSE"}

[project.optional-dependencies]
fetch = ["gdown>=5.2.0"]
vis = ["rerun-sdk>=0.18.2"]

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project.scripts]
evalio = "evalio.cli:main"

[tool.uv]
# TODO: Options this reinstall package somehow?
# reinstall-package = ["evalio"]
dev-dependencies = [
    "cmake>=3.30.3",
    "pip>=24.2",
    "pybind11>=2.13.6",
    "scikit-build-core>=0.10.7",
]
