"""
This type stub file was generated by pyright.
"""

from .distinctipy import (
    BLACK,
    BLUE,
    CORNERS,
    CYAN,
    GREEN,
    INTERIOR,
    MAGENTA,
    MID_FACE,
    POINTS_OF_INTEREST,
    RED,
    WHITE,
    YELLOW,
    get_colors,
)

"""
distinctipy is a lightweight python package providing functions to generate
colours that are visually distinct from one another.

Example:
    >>> import distinctipy
    >>> distinctipy.get_colors(5)
    [(0, 1, 0), (1, 0, 1), (0, 0.5, 1), (1, 0.5, 0), (0.5, 0.75, 0.5)]
"""
name = ...
__version__ = ...
__external__ = ...
__protected__ = ...
__autogen_notes__ = ...
__all__ = [
    "BLACK",
    "BLUE",
    "CORNERS",
    "CYAN",
    "GREEN",
    "INTERIOR",
    "MAGENTA",
    "MID_FACE",
    "POINTS_OF_INTEREST",
    "RED",
    "WHITE",
    "YELLOW",
    "get_colors",
    "name",
]
