ARG ARCH=x86_64
ARG GLIBC=2_28
ARG VERSION=latest
FROM quay.io/pypa/manylinux_${GLIBC}_${ARCH}:${VERSION}

COPY ./ ./
RUN ./install_deps_manylinux.sh

# locally installed libs are stored here - make sure they can be found
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64

# Add a user for dev work
ARG USERNAME=evalio
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME