"""
This type stub file was generated by pyright.
"""

from .download import download
from .download_folder import download_folder

__version__ = ...

__all__ = [
    "download",
    "download_folder",
]
