"""
This type stub file was generated by pyright.
"""

from typing import List

MAX_NUMBER_FILES = ...

class _GoogleDriveFile:
    TYPE_FOLDER = ...
    def __init__(self, id, name, type, children=...) -> None: ...
    def is_folder(self): ...

GoogleDriveFileToDownload = ...

def download_folder(
    url: str = ...,
    id: str = ...,
    output: str = ...,
    quiet: bool = ...,
    proxy: str = ...,
    speed: float = ...,
    use_cookies: bool = ...,
    remaining_ok: bool = ...,
    verify: bool | str = ...,
    user_agent: str = ...,
    skip_download: bool = ...,
    resume: bool = ...,
) -> List[str]:
    """Downloads entire folder from URL.

    Parameters
    ----------
    url: str
        URL of the Google Drive folder.
        Must be of the format 'https://drive.google.com/drive/folders/{url}'.
    id: str
        Google Drive's folder ID.
    output: str, optional
        String containing the path of the output folder.
        Defaults to current working directory.
    quiet: bool, optional
        Suppress terminal output.
    proxy: str, optional
        Proxy.
    speed: float, optional
        Download byte size per second (e.g., 256KB/s = 256 * 1024).
    use_cookies: bool, optional
        Flag to use cookies. Default is True.
    verify: bool or string
        Either a bool, in which case it controls whether the server's TLS
        certificate is verified, or a string, in which case it must be a path
        to a CA bundle to use. Default is True.
    user_agent: str, optional
        User-agent to use in the HTTP request.
    skip_download: bool, optional
        If True, return the list of files to download without downloading them.
        Defaults to False.
    resume: bool
        Resume interrupted transfers.
        Completed output files will be skipped.
        Partial tempfiles will be reused, if the transfer is incomplete.
        Default is False.

    Returns
    -------
    files: List[str] or List[GoogleDriveFileToDownload] or None
        If dry_run is False, list of local file paths downloaded or None if failed.
        If dry_run is True, list of GoogleDriveFileToDownload that contains
        id, path, and local_path.

    Example
    -------
    gdown.download_folder(
        "https://drive.google.com/drive/folders/" +
        "1ZXEhzbLRLU1giKKRJkjm8N04cO_JoYE2",
    )
    """
    ...
